# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PPDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for PPDemo


pod 'AFNetworking'
pod 'FMDB'
pod 'SDWebImage'
pod 'MBProgressHUD'
pod 'MJRefresh'
pod 'Masonry'


end
